version: '3.4'
services:
  stader.avado.dnp.dappnode.eth:
    image: 'stader.avado.dnp.dappnode.eth:0.0.4'
    build:
      context: ./build
      args:
        STADER_VERSION: v0.4.0-avado
    volumes:
      - 'data:/.stader/'
    environment:
      - NETWORK=prater
      - EXECUTIONCLIENT=geth
      - CONSENSUSCLIENT=teku
      - EXTRA_OPTS=
    ports:
      - '80:80'
      - '9999:9999'
volumes:
  data: {}
