version: '3.4'
services:
  stader.avado.dnp.dappnode.eth:
    image: 'stader.avado.dnp.dappnode.eth:0.0.1'
    build:
      context: ./build
      args:
        STADER_VERSION: v0.3.0-beta
    volumes:
      - 'data:/.stader/'
    environment:
      - EXTRA_OPTS=
    ports:
      - '80:80'
      - '9999:9999'
volumes:
  data: {}
